//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeListWebApplication.EmployeeListService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://maersk.com/webservice", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://maersk.com/webservice", ConfigurationName="EmployeeListService.EmployeeListSoap")]
    public interface EmployeeListSoap {
        
        // CODEGEN: Generating message contract since element name employeeName from namespace http://maersk.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://maersk.com/webservice/AddEmployee", ReplyAction="*")]
        EmployeeListWebApplication.EmployeeListService.AddEmployeeResponse AddEmployee(EmployeeListWebApplication.EmployeeListService.AddEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://maersk.com/webservice/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.AddEmployeeResponse> AddEmployeeAsync(EmployeeListWebApplication.EmployeeListService.AddEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name GetEmployeesResult from namespace http://maersk.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://maersk.com/webservice/GetEmployees", ReplyAction="*")]
        EmployeeListWebApplication.EmployeeListService.GetEmployeesResponse GetEmployees(EmployeeListWebApplication.EmployeeListService.GetEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://maersk.com/webservice/GetEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.GetEmployeesResponse> GetEmployeesAsync(EmployeeListWebApplication.EmployeeListService.GetEmployeesRequest request);
        
        // CODEGEN: Generating message contract since element name updatedName from namespace http://maersk.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://maersk.com/webservice/UpdateEmployee", ReplyAction="*")]
        EmployeeListWebApplication.EmployeeListService.UpdateEmployeeResponse UpdateEmployee(EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://maersk.com/webservice/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.UpdateEmployeeResponse> UpdateEmployeeAsync(EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name DeleteEmployeeResult from namespace http://maersk.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://maersk.com/webservice/DeleteEmployee", ReplyAction="*")]
        EmployeeListWebApplication.EmployeeListService.DeleteEmployeeResponse DeleteEmployee(EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://maersk.com/webservice/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.DeleteEmployeeResponse> DeleteEmployeeAsync(EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployee", Namespace="http://maersk.com/webservice", Order=0)]
        public EmployeeListWebApplication.EmployeeListService.AddEmployeeRequestBody Body;
        
        public AddEmployeeRequest() {
        }
        
        public AddEmployeeRequest(EmployeeListWebApplication.EmployeeListService.AddEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://maersk.com/webservice")]
    public partial class AddEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string employeeName;
        
        public AddEmployeeRequestBody() {
        }
        
        public AddEmployeeRequestBody(string employeeName) {
            this.employeeName = employeeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeeResponse", Namespace="http://maersk.com/webservice", Order=0)]
        public EmployeeListWebApplication.EmployeeListService.AddEmployeeResponseBody Body;
        
        public AddEmployeeResponse() {
        }
        
        public AddEmployeeResponse(EmployeeListWebApplication.EmployeeListService.AddEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://maersk.com/webservice")]
    public partial class AddEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEmployeeResult;
        
        public AddEmployeeResponseBody() {
        }
        
        public AddEmployeeResponseBody(string AddEmployeeResult) {
            this.AddEmployeeResult = AddEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployees", Namespace="http://maersk.com/webservice", Order=0)]
        public EmployeeListWebApplication.EmployeeListService.GetEmployeesRequestBody Body;
        
        public GetEmployeesRequest() {
        }
        
        public GetEmployeesRequest(EmployeeListWebApplication.EmployeeListService.GetEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployeesRequestBody {
        
        public GetEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployeesResponse", Namespace="http://maersk.com/webservice", Order=0)]
        public EmployeeListWebApplication.EmployeeListService.GetEmployeesResponseBody Body;
        
        public GetEmployeesResponse() {
        }
        
        public GetEmployeesResponse(EmployeeListWebApplication.EmployeeListService.GetEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://maersk.com/webservice")]
    public partial class GetEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeListWebApplication.EmployeeListService.ArrayOfString GetEmployeesResult;
        
        public GetEmployeesResponseBody() {
        }
        
        public GetEmployeesResponseBody(EmployeeListWebApplication.EmployeeListService.ArrayOfString GetEmployeesResult) {
            this.GetEmployeesResult = GetEmployeesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployee", Namespace="http://maersk.com/webservice", Order=0)]
        public EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequestBody Body;
        
        public UpdateEmployeeRequest() {
        }
        
        public UpdateEmployeeRequest(EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://maersk.com/webservice")]
    public partial class UpdateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int index;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string updatedName;
        
        public UpdateEmployeeRequestBody() {
        }
        
        public UpdateEmployeeRequestBody(int index, string updatedName) {
            this.index = index;
            this.updatedName = updatedName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeResponse", Namespace="http://maersk.com/webservice", Order=0)]
        public EmployeeListWebApplication.EmployeeListService.UpdateEmployeeResponseBody Body;
        
        public UpdateEmployeeResponse() {
        }
        
        public UpdateEmployeeResponse(EmployeeListWebApplication.EmployeeListService.UpdateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://maersk.com/webservice")]
    public partial class UpdateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateEmployeeResult;
        
        public UpdateEmployeeResponseBody() {
        }
        
        public UpdateEmployeeResponseBody(string UpdateEmployeeResult) {
            this.UpdateEmployeeResult = UpdateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployee", Namespace="http://maersk.com/webservice", Order=0)]
        public EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequestBody Body;
        
        public DeleteEmployeeRequest() {
        }
        
        public DeleteEmployeeRequest(EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://maersk.com/webservice")]
    public partial class DeleteEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int index;
        
        public DeleteEmployeeRequestBody() {
        }
        
        public DeleteEmployeeRequestBody(int index) {
            this.index = index;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeResponse", Namespace="http://maersk.com/webservice", Order=0)]
        public EmployeeListWebApplication.EmployeeListService.DeleteEmployeeResponseBody Body;
        
        public DeleteEmployeeResponse() {
        }
        
        public DeleteEmployeeResponse(EmployeeListWebApplication.EmployeeListService.DeleteEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://maersk.com/webservice")]
    public partial class DeleteEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteEmployeeResult;
        
        public DeleteEmployeeResponseBody() {
        }
        
        public DeleteEmployeeResponseBody(string DeleteEmployeeResult) {
            this.DeleteEmployeeResult = DeleteEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeListSoapChannel : EmployeeListWebApplication.EmployeeListService.EmployeeListSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeListSoapClient : System.ServiceModel.ClientBase<EmployeeListWebApplication.EmployeeListService.EmployeeListSoap>, EmployeeListWebApplication.EmployeeListService.EmployeeListSoap {
        
        public EmployeeListSoapClient() {
        }
        
        public EmployeeListSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeListSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeListSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeListSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeListWebApplication.EmployeeListService.AddEmployeeResponse EmployeeListWebApplication.EmployeeListService.EmployeeListSoap.AddEmployee(EmployeeListWebApplication.EmployeeListService.AddEmployeeRequest request) {
            return base.Channel.AddEmployee(request);
        }
        
        public string AddEmployee(string employeeName) {
            EmployeeListWebApplication.EmployeeListService.AddEmployeeRequest inValue = new EmployeeListWebApplication.EmployeeListService.AddEmployeeRequest();
            inValue.Body = new EmployeeListWebApplication.EmployeeListService.AddEmployeeRequestBody();
            inValue.Body.employeeName = employeeName;
            EmployeeListWebApplication.EmployeeListService.AddEmployeeResponse retVal = ((EmployeeListWebApplication.EmployeeListService.EmployeeListSoap)(this)).AddEmployee(inValue);
            return retVal.Body.AddEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.AddEmployeeResponse> EmployeeListWebApplication.EmployeeListService.EmployeeListSoap.AddEmployeeAsync(EmployeeListWebApplication.EmployeeListService.AddEmployeeRequest request) {
            return base.Channel.AddEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.AddEmployeeResponse> AddEmployeeAsync(string employeeName) {
            EmployeeListWebApplication.EmployeeListService.AddEmployeeRequest inValue = new EmployeeListWebApplication.EmployeeListService.AddEmployeeRequest();
            inValue.Body = new EmployeeListWebApplication.EmployeeListService.AddEmployeeRequestBody();
            inValue.Body.employeeName = employeeName;
            return ((EmployeeListWebApplication.EmployeeListService.EmployeeListSoap)(this)).AddEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeListWebApplication.EmployeeListService.GetEmployeesResponse EmployeeListWebApplication.EmployeeListService.EmployeeListSoap.GetEmployees(EmployeeListWebApplication.EmployeeListService.GetEmployeesRequest request) {
            return base.Channel.GetEmployees(request);
        }
        
        public EmployeeListWebApplication.EmployeeListService.ArrayOfString GetEmployees() {
            EmployeeListWebApplication.EmployeeListService.GetEmployeesRequest inValue = new EmployeeListWebApplication.EmployeeListService.GetEmployeesRequest();
            inValue.Body = new EmployeeListWebApplication.EmployeeListService.GetEmployeesRequestBody();
            EmployeeListWebApplication.EmployeeListService.GetEmployeesResponse retVal = ((EmployeeListWebApplication.EmployeeListService.EmployeeListSoap)(this)).GetEmployees(inValue);
            return retVal.Body.GetEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.GetEmployeesResponse> EmployeeListWebApplication.EmployeeListService.EmployeeListSoap.GetEmployeesAsync(EmployeeListWebApplication.EmployeeListService.GetEmployeesRequest request) {
            return base.Channel.GetEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.GetEmployeesResponse> GetEmployeesAsync() {
            EmployeeListWebApplication.EmployeeListService.GetEmployeesRequest inValue = new EmployeeListWebApplication.EmployeeListService.GetEmployeesRequest();
            inValue.Body = new EmployeeListWebApplication.EmployeeListService.GetEmployeesRequestBody();
            return ((EmployeeListWebApplication.EmployeeListService.EmployeeListSoap)(this)).GetEmployeesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeListWebApplication.EmployeeListService.UpdateEmployeeResponse EmployeeListWebApplication.EmployeeListService.EmployeeListSoap.UpdateEmployee(EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public string UpdateEmployee(int index, string updatedName) {
            EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequest inValue = new EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequest();
            inValue.Body = new EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequestBody();
            inValue.Body.index = index;
            inValue.Body.updatedName = updatedName;
            EmployeeListWebApplication.EmployeeListService.UpdateEmployeeResponse retVal = ((EmployeeListWebApplication.EmployeeListService.EmployeeListSoap)(this)).UpdateEmployee(inValue);
            return retVal.Body.UpdateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.UpdateEmployeeResponse> EmployeeListWebApplication.EmployeeListService.EmployeeListSoap.UpdateEmployeeAsync(EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.UpdateEmployeeResponse> UpdateEmployeeAsync(int index, string updatedName) {
            EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequest inValue = new EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequest();
            inValue.Body = new EmployeeListWebApplication.EmployeeListService.UpdateEmployeeRequestBody();
            inValue.Body.index = index;
            inValue.Body.updatedName = updatedName;
            return ((EmployeeListWebApplication.EmployeeListService.EmployeeListSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeListWebApplication.EmployeeListService.DeleteEmployeeResponse EmployeeListWebApplication.EmployeeListService.EmployeeListSoap.DeleteEmployee(EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployee(request);
        }
        
        public string DeleteEmployee(int index) {
            EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequest inValue = new EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequest();
            inValue.Body = new EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequestBody();
            inValue.Body.index = index;
            EmployeeListWebApplication.EmployeeListService.DeleteEmployeeResponse retVal = ((EmployeeListWebApplication.EmployeeListService.EmployeeListSoap)(this)).DeleteEmployee(inValue);
            return retVal.Body.DeleteEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.DeleteEmployeeResponse> EmployeeListWebApplication.EmployeeListService.EmployeeListSoap.DeleteEmployeeAsync(EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeListWebApplication.EmployeeListService.DeleteEmployeeResponse> DeleteEmployeeAsync(int index) {
            EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequest inValue = new EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequest();
            inValue.Body = new EmployeeListWebApplication.EmployeeListService.DeleteEmployeeRequestBody();
            inValue.Body.index = index;
            return ((EmployeeListWebApplication.EmployeeListService.EmployeeListSoap)(this)).DeleteEmployeeAsync(inValue);
        }
    }
}
